server:
  port: ${PORT:8084}
  servlet:
    context-path: /testing

spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        jdbc:
          batch_size=10
  flyway:
    enabled: true
    locations: db/migration/testing

springdoc:
  swagger-ui:
    enabled: true
