server:
  port: 8085

keycloak:
  host: localhost:8888
  realm: studyjam
  certs-id: K8aUK_QgRhBJ1mqLCXn5skBShc5PSY1lsLeKZyYboYE
  client-id: spring
  client-secret: mjnoLPMym2ZFSkKRKXDV3vnF7yENMKTR
  client-grant-type: client_credentials
  user-grant-type: password

  certs-url: http://${keycloak.host}/auth/realms/${keycloak.realm}/protocol/openid-connect/certs
  token-url: http://${keycloak.host}/auth/realms/${keycloak.realm}/protocol/openid-connect/token
  user-info-url: http://${keycloak.host}/auth/realms/${keycloak.realm}/protocol/openid-connect/userinfo
  users-url: http://${keycloak.host}/auth/admin/realms/${keycloak.realm}/users
  reset-password-url: http://${keycloak.host}/auth/admin/realms/${keycloak.realm}/users/{sub}/reset-password

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./auth_db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console.enabled: true
