server:
  port: 8085

application:
  keycloak:
    host: localhost:8888
    realm: studyjam

    certs-id: ${KEYCLOAK_REALM_CERTS_RS256}
    client-id: spring
    client-secret: ${KEYCLOAK_CLIENT_SECRET}
    client-grant-type: client_credentials
    user-grant-type: password

    certs-url: http://${application.keycloak.host}/auth/realms/${application.keycloak.realm}/protocol/openid-connect/certs
    token-url: http://${application.keycloak.host}/auth/realms/${application.keycloak.realm}/protocol/openid-connect/token
    user-info-url: http://${application.keycloak.host}/auth/realms/${application.keycloak.realm}/protocol/openid-connect/userinfo
    users-url: http://${application.keycloak.host}/auth/admin/realms/${application.keycloak.realm}/users
    reset-password-url: http://${application.keycloak.host}/auth/admin/realms/${application.keycloak.realm}/users/{sub}/reset-password

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./auth_db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console.enabled: true
