server:
  port: 8081
  servlet:
    context-path: /external-files

s3:
  url: http://localhost
  host: 9000
  bucket-name: surf
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./ext_db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      org.hibernate.envers:
        audit_table_suffix: _audit
        revision_type_field_name: revision_type
        revision_field_name: revision_id
  h2:
    console.enabled: true
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

springdoc:
  swagger-ui:
    enabled: true

external-files:
  claim-interval-seconds: 30
