server:
  port: 8081
  servlet:
    context-path: /api
s3:
  access-key: 8PmDRiPhS0cPjjOQ
  secret-key: m8W8wHgTS8wv3jfs432qGuc50x05qa3o
  bucket-name: surf
  url: http://localhost
  host: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/surf_db
    username: postgres
    password: revan12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      org.hibernate.envers:
          audit_table_suffix: _audit
          revision_type_field_name: revision_type
          revision_field_name: revision_id
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
springdoc:
  swagger-ui:
    enabled: true



