server:
  port: 8081
  servlet:
    context-path: /api

s3:
  access-key: surf
  secret-key: surfpassword
  bucket-name: surf
  url: http://localhost
  host: 9000

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./ext_db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

springdoc:
  swagger-ui:
    enabled: true

external-files:
  claim-interval-seconds: ${CLAIM_INTERVAL_SECONDS}
