server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/surf_db
    username: sas
    password: sas
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      org.hibernate.envers:
        audit_table_suffix: _audit
        revision_type_field_name: revision_type
        revision_field_name: revision_id

services:
  report:
    base_url: http://localhost:8082
  testing:
    url: http://0.0.0.0:8084/testing
  external-files:
    url: http://0.0.0.0:8181/external-files/files/file