server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/surf_db
    username: postgres
    password: revan12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true