server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./core_db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
  flyway:
    enabled: false

springdoc:
  swagger-ui:
    enabled: true

authService:
  credentialsServiceApi: http://localhost:8085/credentialsServiceApi

externalFiles:
  s3FileServiceApi: http://localhost:8081/api/s3FileServiceApi
