server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/surf_db
    username: postgres
    password: revan12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      client-id: service-core
      properties:
        spring.json.add.type.headers: false


springdoc:
  swagger-ui:
    enabled: true

authService:
  credentialsServiceApi: http://localhost:8085/credentialsServiceApi

externalFiles:
  s3FileServiceApi: http://localhost:8081/api/s3FileServiceApi