server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/squamish
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true